### PR TITLE
Respect separators when sorting

### LINKED ISSUE #1: Separators should be respected when sorting
I'd like to request that SSB leave separators alone and treat the items before and after as distinct sorting areas.

Currently, when presented with a folder that looks like this:

    [Folder 1]
    [Folder 4]
    [Folder 3]
    ---
    [Folder 2]
    ---
    Bookmark 1

...SSB does this:

    [Folder 1]
    [Folder 2]
    [Folder 3]
    [Folder 4]
    ---
    ---
    Bookmark 1

...but it would make more sense if it did this:

    [Folder 1]
    [Folder 3]
    [Folder 4]
    ---
    [Folder 2]
    ---
    Bookmark 1

### PR DESCRIPTION
**Pull request by blackwind**
Resolves #1.

### CODE REVIEW

**Comment by blackwind** [comment]
I'm assuming my pull request hasn't been approved yet because I removed functionality, so I've gone ahead and restored sortBy. Best of both worlds now.

**Comment by ariacorrente** [comment]
The cause was lack of free time, in the next days I hope to find time to review your pull request. Your code changes practically all the sorting code, i need some time to test (and remember how my stuff worked).

In the meantime I thank you for your work.

**Comment by blackwind** [comment]
Still hoping to see this and #4 merged and released at some point. :smiley:

**Comment by ariacorrente** [comment]
#4 has been merged, thanks for the optimization :+1: 

#3 is a huge change that complicates the addon quite a lot. I like the fact that this "sorting addon" don't have any sorting code. The change have even a performance impact, but it's small, at least for my system.

I'm evaluating the possibility to rewrite the addon using the "WebExtensions" technology. In this case I probably need to write the sorting code so the feature to respect the separator can be added without changing the spirit of the addon.

For now I prefer to don't merge the pull request. I count to use your code in the future, thanks.

**Comment by blackwind** [comment]
I'm going ahead and purging the repo from my account. In case you end up needing it in the future, here's the full content of the changed file:

```
/*
Copyright 2014, Nicola Felice

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

"use strict";

var {
    Cc, Ci
} = require("chrome");
var {
    emit, on, once, off
} = require("sdk/event/core");
var timer = require("sdk/timers");
var simplePrefs = require("sdk/simple-prefs");
var historyService = Cc["@mozilla.org/browser/nav-history-service;1"]
    .getService(Ci.nsINavHistoryService);
var bmsvc = Cc["@mozilla.org/browser/nav-bookmarks-service;1"]
    .getService(Ci.nsINavBookmarksService);
var options = historyService.getNewQueryOptions();

// Set to true when a sorting is running. This allows the current sorting
// procedure not to trigger a new sorting request by the bookmark listener
var alreadyRunning = false;
// Queue of folder id to be sorted
var folderId = [];
/*
When true will be sorted also the child folders of the one in the queue.
This is declared at module's root level because i don't know how to add
parameters to the callback function  used by the timer.
*/
var isRecursive = false;
//Folder ids not to be sorted
var blacklist = [];

function setBlacklist(list) {
    blacklist = list;
}

function setBatchMode(isBatchMode) {
    console.log("BatchMode set to " + isBatchMode + "\n");
    //Stop if i'm sorting now
    if (isBatchMode) {
        isRecursive = false;
        folderId = [];
        alreadyRunning = true;
    } else {
        alreadyRunning = false;
    }
}

function getProperty(itemId) {
    try {
        if (simplePrefs.prefs.sortBy == 1) {
            return String(bmsvc.getBookmarkURI(itemId).spec) || "";
        } else if (simplePrefs.prefs.sortBy == 2) {
            return String(bmsvc.getItemDateAdded(itemId)) || "";
        } else {
            return String(bmsvc.getItemTitle(itemId)) || "";
        }
    } catch (e1) {
        try {
            return String(bmsvc.getItemTitle(itemId)) || "";
        } catch (e2) {
            return "";
        }
    }
}

function getSortedKeys(obj) {
    return Object.keys(obj).sort(function(a, b) { return obj[a].toLowerCase().localeCompare(obj[b].toLowerCase()); });
}

function isBlacklisted(folderId) {
    for (var i = 0; i < blacklist.length; i++) {
        if (blacklist[i] === folderId) {
            return true;
        }
    }
    return false;
}

/*
1. get the first bookmark id stored in the array "folderId"
2. check if blacklisted and skip in this case
3. get all items in the folder
4. sort using the correct function (with folder first or not)
5. if there are more folders in the folderId array launch the timer to go on
*/
function sortItems() {
    var i, node, sepCount = 0, bookmarks = [{}], folders = [{}], order = [];
    alreadyRunning = true;
    var id = folderId.pop();
    var title = bmsvc.getItemTitle(id);

    //Check if blacklisted
    if (isBlacklisted(id)) {
        console.log("Skipping blacklisted folder: " + title + " with id " + id + "\n");
    } else {
        //Get folder content
        console.log("I'm sorting folder: " + title + " with id " + id + "\n");
        var query = historyService.getNewQuery();
        query.setFolders([id], 1);
        var result = historyService.executeQuery(query, options);
        var rootNode = result.root;
        rootNode.containerOpen = true;

        //Sort items
        for (i = 0; i < rootNode.childCount; i++) {
            node = rootNode.getChild(i);
            if (node.type === node.RESULT_TYPE_SEPARATOR) {
                sepCount++;
                bookmarks[sepCount] = {};
                folders[sepCount] = {};
            } else if (node.type === node.RESULT_TYPE_FOLDER) {
                folders[sepCount][node.itemId] = getProperty(node.itemId);
                if (isRecursive) {
                    folderId.push(node.itemId);
                }
            } else {
                bookmarks[sepCount][node.itemId] = getProperty(node.itemId);
            }
        }

        for (i = 0; i <= sepCount; i++) {
            if (simplePrefs.prefs.mustSortFolderFirst || simplePrefs.prefs.sortBy == 1) {
                order = order.concat(getSortedKeys(folders[i]), getSortedKeys(bookmarks[i]));
            } else {
                order = order.concat(getSortedKeys(Object.assign(folders[i], bookmarks[i])));
            }
            order.push(-1);
        }

        for (i in order) {
            if (order[i] != -1) {
                bmsvc.setItemIndex(order[i], i);
            }
        }
    }

    //Keep processing queued folders
    if (folderId.length > 0) {
        timer.setTimeout(sortItems, 0);
    } else {
        alreadyRunning = false;
        isRecursive = false;
        emit(exports, "completed");
    }
}

/*
Initialize the query options and call sortItems to start the effective sorting
*/
function sortFolder(newId, sortChild) {
    if (!alreadyRunning) {
        alreadyRunning = true;
        folderId.push(newId);
        isRecursive = sortChild;

        //Show work in progres dialog
        if (isRecursive) {
            emit(exports, "sortStarted");
        }

        timer.setTimeout(sortItems, 100);
    }
}

/*
Sort recursivly from the root folder
This is usefull to avoid to include the bookmark service in other places only to
access the bookmarkMenuFolder enumerator.
*/
function sortEverything() {
    sortFolder(bmsvc.bookmarksMenuFolder, true);
}

exports.sortFolder = sortFolder;
exports.sortEverything = sortEverything;
exports.setBlacklist = setBlacklist;
exports.setBatchMode = setBatchMode;

exports.on = on.bind(null, exports);
exports.once = once.bind(null, exports);
exports.removeListener = function removeListener(type, listener) {
    off(exports, type, listener);
};
```

**Comment by blackwind** [comment]
Here's the latest version of the file with all your recent changes applied:

```
/*
Copyright 2014, Nicola Felice

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

"use strict";

var {
    Cc, Ci
} = require("chrome");
var {
    emit, on, once, off
} = require("sdk/event/core");
var timer = require("sdk/timers");
var simplePrefs = require("sdk/simple-prefs");
var historyService = Cc["@mozilla.org/browser/nav-history-service;1"]
    .getService(Ci.nsINavHistoryService);
var bmsvc = Cc["@mozilla.org/browser/nav-bookmarks-service;1"]
    .getService(Ci.nsINavBookmarksService);
var options = historyService.getNewQueryOptions();

// Set to true when a sorting is running. This allows the current sorting
// procedure not to trigger a new sorting request by the bookmark listener
var alreadyRunning = false;
// Queue of folder id to be sorted
var folderId = [];
/*
When true will be sorted also the child folders of the one in the queue.
This is declared at module's root level because i don't know how to add
parameters to the callback function  used by the timer.
*/
var isRecursive = false;
//Folder ids not to be sorted
var blacklist = [];

function setBlacklist(list) {
    blacklist = list;
}

function setBatchMode(isBatchMode) {
    console.log("BatchMode set to " + isBatchMode + "\n");
    //Stop if i'm sorting now
    if (isBatchMode) {
        isRecursive = false;
        folderId = [];
        alreadyRunning = true;
    } else {
        alreadyRunning = false;
    }
}

function getProperty(itemId) {
    try {
        if (simplePrefs.prefs.sortBy == 1) {
            return String(bmsvc.getBookmarkURI(itemId).spec) || "";
        } else if (simplePrefs.prefs.sortBy == 2) {
            return String(bmsvc.getItemDateAdded(itemId)) || "";
        } else {
            return String(bmsvc.getItemTitle(itemId)) || "";
        }
    } catch (e1) {
        try {
            return String(bmsvc.getItemTitle(itemId)) || "";
        } catch (e2) {
            return "";
        }
    }
}

function getSortedKeys(obj) {
    return Object.keys(obj).sort(function(a, b) { return obj[a].toLowerCase().localeCompare(obj[b].toLowerCase()); });
}

function isBlacklisted(folderId) {
    for (var i = 0; i < blacklist.length; i++) {
        if (blacklist[i] === folderId) {
            return true;
        }
    }
    return false;
}

/*
1. get the first bookmark id stored in the array "folderId"
2. check if blacklisted and skip in this case
3. get all items in the folder
4. sort using the correct function (with folder first or not)
5. if there are more folders in the folderId array launch the timer to go on
*/
function sortItems() {
    if (folderId.length === 0)
      return;

    var i, node, sepCount = 0, bookmarks = [{}], folders = [{}], order = [];
    alreadyRunning = true;
    var id = folderId.pop();
    var title = bmsvc.getItemTitle(id);

    //Check if blacklisted
    if (isBlacklisted(id)) {
        console.log("Skipping blacklisted folder: " + title + " with id " + id + "\n");
    } else {
        //Get folder content
        console.log("I'm sorting folder: " + title + " with id " + id + "\n");
        var query = historyService.getNewQuery();
        query.setFolders([id], 1);
        var result = historyService.executeQuery(query, options);
        var rootNode = result.root;
        rootNode.containerOpen = true;

        //Sort items
        for (i = 0; i < rootNode.childCount; i++) {
            node = rootNode.getChild(i);
            if (node.type === node.RESULT_TYPE_SEPARATOR) {
                sepCount++;
                bookmarks[sepCount] = {};
                folders[sepCount] = {};
            } else if (node.type === node.RESULT_TYPE_FOLDER) {
                folders[sepCount][node.itemId] = getProperty(node.itemId);
                if (isRecursive) {
                    folderId.push(node.itemId);
                }
            } else {
                bookmarks[sepCount][node.itemId] = getProperty(node.itemId);
            }
        }

        for (i = 0; i <= sepCount; i++) {
            if (simplePrefs.prefs.mustSortFolderFirst || simplePrefs.prefs.sortBy == 1) {
                order = order.concat(getSortedKeys(folders[i]), getSortedKeys(bookmarks[i]));
            } else {
                order = order.concat(getSortedKeys(Object.assign(folders[i], bookmarks[i])));
            }
            order.push(-1);
        }

        for (i in order) {
            if (order[i] != -1) {
                //Skip sorting if we are in "Bookmark Menu" and option is set
                if (rootNode.itemId === bmsvc.bookmarksMenuFolder &&
                    simplePrefs.prefs.mustSkipRootFolder === true) {
                    console.log("Skipping root folder because of user preference");
                } else {
                  bmsvc.setItemIndex(order[i], i);
                }
            }
        }
    }

    //Keep processing queued folders
    if (folderId.length > 0) {
        timer.setTimeout(sortItems, 0);
    } else {
        alreadyRunning = false;
        isRecursive = false;
        emit(exports, "completed");
    }
}

/*
Initialize the query options and call sortItems to start the effective sorting

newId can be:
- a single bookmark id
- an array of bookmark ids

An array is required for multiple ids because calling too fast sortFolder will
cause the next execution to skip because of the "alreadyRunning" check.
*/
function sortFolder(newId, sortChild) {
    if (!alreadyRunning) {
        alreadyRunning = true;
        isRecursive = sortChild;

        //Push the newId or the newIds in the queue
        if(Array.isArray(newId)) {
            for(var i = 0; i < newId.length; i++) {
                folderId.push(newId[i]);
            }
        } else {
            folderId.push(newId);
        }

        //Show work in progres dialog
        if (isRecursive) {
            emit(exports, "sortStarted");
        }

        timer.setTimeout(sortItems, 100);
    }
}

/*
Sort recursivly the bookmarks menu, the toolbar, the unfiled bookmarks and the
mobile bookmarks.
This is usefull to avoid to include the bookmark service in other places only to
access the bookmarkMenuFolder enumerator.
*/
function sortEverything() {
    var allFolders = [bmsvc.bookmarksMenuFolder,
                      bmsvc.toolbarFolder,
                      bmsvc.unfiledBookmarksFolder,
                      bmsvc.mobileFolder];
    sortFolder(allFolders, true);
}

exports.sortFolder = sortFolder;
exports.sortEverything = sortEverything;
exports.setBlacklist = setBlacklist;
exports.setBatchMode = setBatchMode;

exports.on = on.bind(null, exports);
exports.once = once.bind(null, exports);
exports.removeListener = function removeListener(type, listener) {
    off(exports, type, listener);
};
```

I'd really, really appreciate a merge of this if the WebExtensions port isn't coming any time soon.

**Comment by ariacorrente** [comment]
Hi, the WebExtension port will not be released soon but at least I can say I found a comfortable set of tools to develop the addon. Now I'm writing some tests to familiarize with the WebExtension API and create a more robust base than the current version.

Meanwhile, reading the Mozilla documentation I found the possibility to publish a beta version of the addon to allow some users to test. You came to my mind and I published a version of the addon with your patch as [version 1.1.0-beta1](https://addons.mozilla.org/en-US/firefox/addon/simplesort-bookmarks/versions/beta). The link can also be reached at the bottom of the page in the block "Development channel". This way I can keep the addon without the sorting code and you can use your version without the need to manually install a local unsigned addon.

**Pull request closed without merging**
